variables:
  TEMPLATE_OPTIONS: ""
  TEMPLATE_IMAGE: ""
  TEMPLATE_VERSION: ""
  TEMPLATE_DOCKERFILE: ""

.build-image:
  tags:
    - shell
  before_script:
    - docker login docker.io -u $DOCKER_USER -p $DOCKER_TOKEN
  script:
    - |
      docker build \
        -t $TEMPLATE_IMAGE:$TEMPLATE_VERSION \
        -t $TEMPLATE_IMAGE:latest \
        $TEMPLATE_OPTIONS \
        -f $TEMPLATE_DOCKERFILE .
    - docker push $TEMPLATE_IMAGE:$TEMPLATE_VERSION
    - docker push $TEMPLATE_IMAGE:latest
  after_script:
    - docker logout
    - docker images --filter "dangling=true" --format "{{.Repository}}:{{.Tag}}:{{.ID}}" | grep "$TEMPLATE_IMAGE" | cut -f 3 -d ":" | xargs docker rmi
