variables:
  VERSION:
    value: $CI_COMMIT_REF_SLUG
    description: Nom de la version

include:
  - project: 'labo/cicd-templates'
    ref: master
    file:
      - '/templates/build-docker.gitlab-ci.yml'
      - '/templates/deploy-swarm.gitlab-ci.yml'

build-docker:
  extends: .template-build-docker
  variables:
    PLATFORMS: "linux/arm64"

deploy-stack:
  extends: .template-deploy-stack
  variables:
    INTERNAL_REGISTRY: "true"
  rules:
    - if: $VERSION =~ /^v[0-9]+\.[0-9]+\.[0-9]+$/ || $VERSION =~ /^[0-9]+\.[0-9]+\.[0-9]+$/ || $CI_COMMIT_TAG =~ /^v[0-9]+\.[0-9]+\.[0-9]+$/
      variables:
        APP_IMAGE: $CI_REGISTRY_IMAGE:${VERSION}
    - if: $CI_COMMIT_REF_NAME == "master"
      variables:
        APP_IMAGE: $CI_REGISTRY_IMAGE:latest
    - if: $VERSION != "" || $CI_COMMIT_TAG || ( $CI_COMMIT_REF_NAME && $CI_COMMIT_REF_NAME != "master" )
      variables:
        APP_IMAGE: $CI_REGISTRY_IMAGE/test:${VERSION}

workflow:
  name: 💥 $VERSION - (╯°□°)╯︵ ┻━┻ 💥
  rules:
    - if: $CI_PIPELINE_SOURCE == "web"
      when: always
    - when: never
