include: "/ci/pipelines/.build-image.yml"

variables:
  IMAGE: $DOCKER_USER/$CI_PROJECT_NAME
  VERSION: "1.0.0-SNAPSHOT"

build-environment:
  stage: build
  extends: .build-image
  variables:
    TEMPLATE_IMAGE: $IMAGE-env
    TEMPLATE_VERSION: $VERSION
    TEMPLATE_OPTIONS: ""
    TEMPLATE_DOCKERFILE: ci/Dockerfile.prod-env
  only:
    changes:
      - ci/Dockerfile.prod-env
      - requirements.txt

build-botte:
  stage: build
  extends: .build-image
  variables:
    TEMPLATE_IMAGE: $IMAGE
    TEMPLATE_VERSION: $VERSION
    TEMPLATE_OPTIONS: --build-arg TAG=$VERSION
    TEMPLATE_DOCKERFILE: ci/Dockerfile.prod
  needs:
    - job: build-environment
      optional: true

deploy-botte:
  stage: deploy
  variables:
    PLAYBOOK_NAME: botte_peuplade.yml
    ENVIROMENT: inventory
    VARIABLES: "botte_peuplade_status=present botte_peuplade_version=$VERSION"
  trigger:
    project: nananas/ansible
    branch: master
    strategy: depend
  needs:
    - job: build-botte

workflow:
  rules:
    - if: $CI_PIPELINE_SOURCE == 'web' || $CI_PIPELINE_SOURCE == 'merge_request_event' || $CI_COMMIT_BRANCH == "master"
      when: always
    - when: never
