include:
  - project: 'labo/cicd-templates'
    ref: master
    file:
      - '/templates/build-docker.gitlab-ci.yml'
      - '/templates/deploy-swarm.gitlab-ci.yml'

build-docker:
  extends: .template-build-docker
  variables:
    PLATFORMS: "linux/arm64"

deploy-stack:
  extends: .template-deploy-stack
  variables:
    INTERNAL_REGISTRY: "true"
  rules:
    - if: $CI_COMMIT_TAG =~ /^v[0-9]+\.[0-9]+\.[0-9]+$/
      variables:
        APP_IMAGE: $CI_REGISTRY_IMAGE:$CI_COMMIT_TAG
    - if: $CI_COMMIT_REF_NAME == $CI_DEFAULT_BRANCH
      variables:
        APP_IMAGE: $CI_REGISTRY_IMAGE:latest
    - if: $CI_COMMIT_REF_NAME && $CI_COMMIT_REF_NAME != $CI_DEFAULT_BRANCH
      variables:
        APP_IMAGE: $CI_REGISTRY_IMAGE/test:$CI_COMMIT_REF_NAME

workflow:
  name: $WORKFLOW_NAME
  rules:
    - if: $CI_PIPELINE_SOURCE == "web" && $CI_COMMIT_TAG =~ /^v[0-9]+\.[0-9]+\.[0-9]+$/
      variables:
        WORKFLOW_NAME: 🚀 (╯°□°)╯︵ ┻━┻ $CI_PROJECT_NAME:$CI_COMMIT_TAG 🚀
    - if: $CI_PIPELINE_SOURCE == "push" && $CI_COMMIT_REF_NAME == $CI_DEFAULT_BRANCH
      variables:
        WORKFLOW_NAME: 🤖 (╯°□°)╯︵ ┻━┻ $CI_PROJECT_NAME:latest 🤖
    - if: $CI_PIPELINE_SOURCE == "web" && $CI_COMMIT_REF_NAME && $CI_COMMIT_REF_NAME != $CI_DEFAULT_BRANCH
      variables:
        WORKFLOW_NAME: 🚚 Petit test... Tchou Tchou 🚚
    - when: never
