include:
  - component: $COMPONENTS/docker/docker-build@1.0.0
    inputs:
      stage: "build"
      image-platforms: "linux/amd64"
      image-dockerfile: ".gitlab/Dockerfile"
  - project: "labo/cicd-templates"
    ref: master
    file:
      - "/templates/deploy-swarm.gitlab-ci.yml"

deploy-stack:
  extends: .template-deploy-stack
  variables:
    INTERNAL_REGISTRY: "true"
    DOCKER_COMPOSE_FILE: ".gitlab/docker-compose.yml"
  rules:
    - if: $CI_COMMIT_TAG =~ /^v[0-9]+\.[0-9]+\.[0-9]+$/
      variables:
        APP_IMAGE: $CI_REGISTRY_IMAGE:$CI_COMMIT_TAG
    - if: $CI_COMMIT_REF_NAME == $CI_DEFAULT_BRANCH
      variables:
        APP_IMAGE: $CI_REGISTRY_IMAGE:latest
    - if: $CI_COMMIT_REF_NAME && $CI_COMMIT_REF_NAME != $CI_DEFAULT_BRANCH
      variables:
        APP_IMAGE: $CI_REGISTRY_IMAGE/test:$CI_COMMIT_REF_NAME

workflow:
  name: $WORKFLOW_NAME
  rules:
    - if: $CI_PIPELINE_SOURCE == "web" && $CI_COMMIT_TAG =~ /^v[0-9]+\.[0-9]+\.[0-9]+$/
      variables:
        WORKFLOW_NAME: 🚀 (╯°□°)╯︵ ┻━┻ $CI_PROJECT_NAME:$CI_COMMIT_TAG 🚀
    - if: $CI_PIPELINE_SOURCE == "push" && $CI_COMMIT_REF_NAME == $CI_DEFAULT_BRANCH
      variables:
        WORKFLOW_NAME: 🤖 (╯°□°)╯︵ ┻━┻ $CI_PROJECT_NAME:latest 🤖
    - if: $CI_PIPELINE_SOURCE == "web" && $CI_COMMIT_REF_NAME && $CI_COMMIT_REF_NAME != $CI_DEFAULT_BRANCH
      variables:
        WORKFLOW_NAME: 🚚 Petit test... Tchou Tchou 🚚
    - when: never
