version: "3"

networks:
  cloud-botte:

volumes:
  ollama: {}

services:
  ollama:
    image: ollama/ollama:0.1.41
    volumes:
      - ollama:/root/.ollama
    networks:
      - cloud-botte
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints: [node.hostname == nasticot]
      restart_policy:
        condition: on-failure

  bot:
    image: ${APP_IMAGE}
    environment:
      # BOT
      - BOTTE_ENV=production
      - BOTTE_NAME=Duc La Botte De Terre
      - BOTTE_VERSION=${VERSION}
      - BOTTE_TOKEN=${BOT_TOKEN}
      - BOTTE_PREFIX=/
      # GUILD
      - GUILD_ID=${BOT_GUILD_ID}
      # MINECRAFT
      - MINECRAFT_HOST=${NASTICOT_IP}
      - MINECRAFT_PORT=${NASTICOT_PORT}
      - MINECRAFT_USERNAME=${MC_USERNAME}
      - MINECRAFT_PASSWORD=${MC_PASSWORD}
      # BLAGUES
      - BLAGUE_API_TOKEN=${BLAGUE_API_TOKEN}
      # ZORBLORT
      - ZORBLORT_API=http://ollama:11434
    networks:
      - cloud-botte
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints: [node.hostname == nasticot]
      restart_policy:
        condition: on-failure
