version: '3'

services:
  app:
    image: registry.papierpain.fr/labo/botte-peuplade:${VERSION}
    environment:
      - BOTTE_ENV=production
      - BOTTE_VERSION=${VERSION}
      - BOTTE_TOKEN=${BOT_TOKEN}
      - BOTTE_PREFIX=/
      - BOTTE_MUSIC_CHANNEL=${BOT_MUSIC_CHANNEL}
      - BOTTE_GUILD_ID=${BOT_GUILD_ID}
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints: [node.role == manager]
      restart_policy:
        max_attempts: 3
    networks:
      - cloud-public

networks:
  cloud-public:
    external: true
