version: '3'

configs:
  lavalink-config:
    file: application.yml

services:
  app:
    image: registry.papierpain.fr/labo/botte-peuplade:${VERSION}
    environment:
      # BOT
      - BOTTE_ENV=production
      - BOTTE_NAME=Duc La Botte De Terre
      - BOTTE_VERSION=${VERSION}
      - BOTTE_TOKEN=${BOT_TOKEN}
      - BOTTE_PREFIX=/
      # GUILD
      - GUILD_ID=${BOT_GUILD_ID}
      # SPOTIFY
      - SPOTIFY_CLIENT_ID=<id-du-client-spotify>
      - SPOTIFY_CLIENT_SECRET=<secret-du-client-spotify>
      # LAVALINK
      - LAVALINK_HOST=lavalink
      - LAVALINK_PORT=2333
      - LAVALINK_PASSWORD=${BOT_LAVALINK_PASSWORD}
      # MINECRAFT
      - MINECRAFT_HOST=${NASTICOT_IP}
      - MINECRAFT_PORT=${NASTICOT_PORT}
      - MINECRAFT_USERNAME=${MC_USERNAME}
      - MINECRAFT_PASSWORD=${MC_PASSWORD}
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints: [node.role == manager]
    depends_on:
      - lavalink
    networks:
      - cloud-public
      - cloud-botte

  lavalink:
    image: fredboat/lavalink:latest
    deploy:
      restart_policy:
        condition: on-failure
      mode: replicated
      replicas: 1
      placement:
        constraints: [node.role == manager]
    configs:
      - source: lavalink-config
        target: /opt/Lavalink/application.yml
    networks:
      - cloud-botte

networks:
  cloud-public:
    external: true
  cloud-botte:
